# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        name: Check out code
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: pixelthump/tischtenniscounter
          tags: dev
          registry: ghcr.io
          dockerfile: Dockerfile
          username: ${{ secrets.GHRC_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
